# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 07:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 3, 5, 7, 18, 35, 27680, tzinfo=utc)),
        ),
    ]
