# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20170312_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='/temp/img/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
