# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20170313_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='temp/img/'),
        ),
    ]
